name = "zyvon-server"
main = "dist/src/index.js"
compatibility_date = "2025-07-07"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "*"
BETTER_AUTH_URL = "https://zyvon-server.gabriel-gs605.workers.dev"
COOKIE_DOMAIN = ""
