name = "zyvon-server"
main = "dist/src/index.js"
compatibility_date = "2025-07-07"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "http://localhost:5173,https://lynkr-web.app,http://localhost:3001"
BETTER_AUTH_URL = "https://db.zyven.online"
