name = "zyven-lynkr-api"
main = "main.py"
compatibility_date = "2025-01-09"
compatibility_flags = ["python"]

[[routes]]
pattern = "api.zyven.online/*"
zone_name = "zyven.online"

[vars]
CORS_ORIGIN = "https://zyven.online"
COOKIE_DOMAIN = ".zyven.online"